# Caps the resources available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.workers.max=1

# Fabric Properties
	# check these on https://fabricmc.net/versions.html
	minecraft_version=26.2
	loader_version=0.19.5
	loom_version=1.16.2

# Mod Properties
	mod_version = 2.0.4.999
	maven_group = com.luneruniverse.minecraft.mod.nbteditor
	archives_base_name = nbteditor

# Dependencies
	fabric_version=0.160.0+26.2
